[package]
name = "reference-runner"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
experiment-4-common.workspace = true
pdfium-render = "=0.9.1"
serde_json.workspace = true
